name: Terraform GitHub Actions
on:
  - push
jobs:
  format:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.13.0
      - name: Terraform Format
        run: terraform fmt -check -recursive
